name: Build and Publish Container Image

on:
  push:
    branches:
        - main
  schedule:
    - cron: '0 14 * * *'


jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check current branch
        if: github.ref != 'refs/heads/main'
        run: exit 0

      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            ./Containerfile
          image: ghcr.io/led0nk/images
          oci: false

      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v2
        id: push
        if: github.event_name != 'pull_request'
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_IMAGES }}
          extra-args: |
            --disable-content-trust

      - name: write cosign key to disk
        run: 'echo "$KEY" > cosign.key'
        shell: bash
        env:
          KEY: ${{ secrets.COSIGN_PRIVATE_KEY}}

      - uses: sigstore/cosign-installer@v3.3.0
        if: github.event_name != 'pull_request'

      - name: Sign container image
        env:
          COSIGN_EXPERIMENTAL: false
          #COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          TAGS: ${{ steps.push.outputs.digest }}

        if: github.event_name != 'pull_request'
        run: |
          cosign sign -y --key cosign.key ${{ steps.registry_case.outputs.lowercase }}/${{ steps.build_image.outputs.image }}@${TAGS}
#env://COSIGN_PRIVATE_KEY
